version: '3.8'
services:
  app:
    image: electricity-v2
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3030:3030
    volumes:
      - ./configs:/app/configs
      - ./logs:/app/logs
    working_dir: /app
    command: node src/gateway/index.js